// Generated by   : ImageConverter 565 Online
// Generated from : wifi_48dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
// Time generated : Mon, 14 Apr 25 21:18:50 +0200  (Server timezone: CET)
// Image Size     : 48x48 pixels
// Memory usage   : 4608 bytes

#pragma once


namespace icons{

    extern unsigned short wifiIcon[48*48];
    extern unsigned short flightIcon[48*48];
    extern unsigned short sensorConIcon[48*48];

};